export const DataSet1: DataKind1[] = [
  { id: 1, title: "Morelia spilotes variegata" },
  { id: 2, title: "Axis axis" },
  { id: 3, title: "Castor canadensis" },
  { id: 4, title: "Elephas maximus bengalensis" },
  { id: 5, title: "Acrantophis madagascariensis" },
  { id: 6, title: "Canis mesomelas" },
  { id: 7, title: "Meles meles" },
  { id: 8, title: "Orcinus orca" },
  { id: 9, title: "Lasiodora parahybana" },
  { id: 10, title: "Echimys chrysurus" },
  { id: 11, title: "Ciconia ciconia" },
  { id: 12, title: "Morelia spilotes variegata" },
  { id: 13, title: "Colaptes campestroides" },
  { id: 14, title: "Catharacta skua" },
  { id: 15, title: "Tamiasciurus hudsonicus" },
  { id: 16, title: "Eolophus roseicapillus" },
  { id: 17, title: "Climacteris melanura" },
  { id: 18, title: "Butorides striatus" },
  { id: 19, title: "Megaderma spasma" },
  { id: 20, title: "Otaria flavescens" },
  { id: 21, title: "Dendrohyrax brucel" },
  { id: 22, title: "Anser anser" },
  { id: 23, title: "Neophron percnopterus" },
  { id: 24, title: "Lasiodora parahybana" },
  { id: 25, title: "Dicrostonyx groenlandicus" },
  { id: 26, title: "Mazama gouazoubira" },
  { id: 27, title: "unavailable" },
  { id: 28, title: "Columba palumbus" },
  { id: 29, title: "Anthropoides paradisea" },
  { id: 30, title: "Haematopus ater" },
  { id: 31, title: "Merops nubicus" },
  { id: 32, title: "Threskionis aethiopicus" },
  { id: 33, title: "Coendou prehensilis" },
  { id: 34, title: "Pseudalopex gymnocercus" },
  { id: 35, title: "Eudyptula minor" },
  { id: 36, title: "Phascolarctos cinereus" },
  { id: 37, title: "Macaca nemestrina" },
  { id: 38, title: "Larus sp." },
  { id: 39, title: "Zenaida galapagoensis" },
  { id: 40, title: "Zalophus californicus" },
  { id: 41, title: "Pycnonotus barbatus" },
  { id: 42, title: "Cynictis penicillata" },
  { id: 43, title: "Theropithecus gelada" },
  { id: 44, title: "Uraeginthus granatina" },
  { id: 45, title: "Trichoglossus chlorolepidotus" },
  { id: 46, title: "Phalacrocorax brasilianus" },
  { id: 47, title: "Ardea cinerea" },
  { id: 48, title: "Spheniscus magellanicus" },
  { id: 49, title: "Dicrurus adsimilis" },
  { id: 50, title: "Tiliqua scincoides" },
  { id: 51, title: "Cercopithecus aethiops" },
  { id: 52, title: "Falco peregrinus" },
  { id: 53, title: "Pseudalopex gymnocercus" },
  { id: 54, title: "Cordylus giganteus" },
  { id: 55, title: "Phoenicopterus ruber" },
  { id: 56, title: "Phaethon aethereus" },
  { id: 57, title: "Merops bullockoides" },
  { id: 58, title: "Larus novaehollandiae" },
  { id: 59, title: "Phylurus milli" },
  { id: 60, title: "Bubalus arnee" },
  { id: 61, title: "Diomedea irrorata" },
  { id: 62, title: "Tapirus terrestris" },
  { id: 63, title: "Mazama americana" },
  { id: 64, title: "Paraxerus cepapi" },
  { id: 65, title: "Hyaena hyaena" },
  { id: 66, title: "Dusicyon thous" },
  { id: 67, title: "Acrantophis madagascariensis" },
  { id: 68, title: "Phalacrocorax albiventer" },
  { id: 69, title: "Ara chloroptera" },
  { id: 70, title: "Chordeiles minor" },
  { id: 71, title: "Gekko gecko" },
  { id: 72, title: "Alopex lagopus" },
  { id: 73, title: "Vulpes cinereoargenteus" },
  { id: 74, title: "Crotalus adamanteus" },
  { id: 75, title: "Varanus salvator" },
  { id: 76, title: "Libellula quadrimaculata" },
  { id: 77, title: "Terathopius ecaudatus" },
  { id: 78, title: "Tockus flavirostris" },
  { id: 79, title: "Tadorna tadorna" },
  { id: 80, title: "Taurotagus oryx" },
  { id: 81, title: "Hymenolaimus malacorhynchus" },
  { id: 82, title: "Genetta genetta" },
  { id: 83, title: "Paraxerus cepapi" },
  { id: 84, title: "Acrobates pygmaeus" },
  { id: 85, title: "Macropus fuliginosus" },
  { id: 86, title: "Myiarchus tuberculifer" },
  { id: 87, title: "Geochelone elegans" },
  { id: 88, title: "Junonia genoveua" },
  { id: 89, title: "Lamprotornis nitens" },
  { id: 90, title: "Lophoaetus occipitalis" },
  { id: 91, title: "Otaria flavescens" },
  { id: 92, title: "Naja haje" },
  { id: 93, title: "Crotalus triseriatus" },
  { id: 94, title: "Geochelone elephantopus" },
  { id: 95, title: "Alcelaphus buselaphus caama" },
  { id: 96, title: "Macropus giganteus" },
  { id: 97, title: "Agouti paca" },
  { id: 98, title: "Haematopus ater" },
  { id: 99, title: "Ursus americanus" },
  { id: 100, title: "Dipodomys deserti" },
];
export const DataSet2: DataKind2[] = [
  { name: "Duobam", description: "Reduced human-resource workforce" },
  {
    name: "Span",
    description: "Function-based local moderator",
    address: "mcondit1@cbc.ca",
  },
  { name: "Cardguard", description: "Inverse high-level focus group" },
  {
    name: "Veribet",
    description: "Multi-lateral zero administration hardware",
    address: "cspratling3@fastcompany.com",
  },
  { name: "Flowdesk", description: "Business-focused grid-enabled structure" },
  { name: "Alpha", description: "Front-line asynchronous database" },
  { name: "Vagram", description: "Networked systematic concept" },
  {
    name: "Sonair",
    description: "Up-sized static artificial intelligence",
    address: "rbuxcy7@list-manage.com",
  },
  {
    name: "Cardify",
    description: "Synergized context-sensitive info-mediaries",
    address: "njentin8@php.net",
  },
  { name: "Fintone", description: "Customer-focused exuding database" },
  { name: "Cardify", description: "Programmable exuding neural-net" },
  {
    name: "Daltfresh",
    description: "Robust multi-state framework",
    address: "hmclarnonb@sourceforge.net",
  },
  { name: "Tin", description: "Operative tangible implementation" },
  {
    name: "Aerified",
    description: "Reduced well-modulated superstructure",
    address: "mswadlinged@goodreads.com",
  },
  { name: "Home Ing", description: "Front-line eco-centric function" },
  {
    name: "Stringtough",
    description: "Grass-roots optimal superstructure",
    address: "wmollnarf@ocn.ne.jp",
  },
  { name: "Trippledex", description: "Phased foreground application" },
  { name: "Asoka", description: "Focused asymmetric success" },
  {
    name: "Voyatouch",
    description: "Operative grid-enabled instruction set",
    address: "rtisuni@abc.net.au",
  },
  { name: "Greenlam", description: "Cross-group explicit definition" },
  { name: "Bigtax", description: "Optimized optimal encryption" },
  {
    name: "Bytecard",
    description: "Pre-emptive foreground matrix",
    address: "ebeedenl@nbcnews.com",
  },
  {
    name: "Trippledex",
    description: "Switchable responsive internet solution",
    address: "areynam@goo.ne.jp",
  },
  {
    name: "Bitwolf",
    description: "Reduced hybrid success",
    address: "lmeredithn@nydailynews.com",
  },
  {
    name: "Kanlam",
    description: "Grass-roots transitional utilisation",
    address: "bkettlestringo@cbsnews.com",
  },
  {
    name: "Trippledex",
    description: "Monitored content-based project",
    address: "cjumelp@latimes.com",
  },
  { name: "Keylex", description: "Synchronised heuristic forecast" },
  { name: "Stronghold", description: "Intuitive needs-based structure" },
  { name: "Latlux", description: "Profit-focused analyzing adapter" },
  { name: "Bitchip", description: "Seamless exuding architecture" },
  { name: "Trippledex", description: "Devolved transitional function" },
  {
    name: "Konklab",
    description: "Public-key optimal flexibility",
    address: "dvlasenkovv@booking.com",
  },
  { name: "Wrapsafe", description: "Cross-group holistic task-force" },
  {
    name: "Domainer",
    description: "Diverse optimal leverage",
    address: "dklimentx@ycombinator.com",
  },
  {
    name: "Veribet",
    description: "Mandatory explicit contingency",
    address: "alaisey@trellian.com",
  },
  {
    name: "Lotstring",
    description: "Fundamental discrete capacity",
    address: "lhumesz@mapquest.com",
  },
  {
    name: "Zathin",
    description: "Assimilated human-resource focus group",
    address: "emcmenemy10@amazonaws.com",
  },
  {
    name: "Lotstring",
    description: "Managed client-server implementation",
    address: "sgriffoen11@washington.edu",
  },
  { name: "Domainer", description: "User-centric bottom-line ability" },
  {
    name: "Hatity",
    description: "Pre-emptive empowering paradigm",
    address: "mcanaan13@ask.com",
  },
  {
    name: "Veribet",
    description: "Distributed systemic projection",
    address: "aphillis14@goo.gl",
  },
  { name: "Job", description: "Fundamental object-oriented website" },
  {
    name: "Bytecard",
    description: "Reactive dynamic help-desk",
    address: "cwalthew16@desdev.cn",
  },
  {
    name: "Zoolab",
    description: "Right-sized value-added access",
    address: "ahartzogs17@chronoengine.com",
  },
  { name: "Aerified", description: "Visionary 3rd generation knowledge base" },
  { name: "Zoolab", description: "Inverse heuristic budgetary management" },
  { name: "Konklab", description: "Implemented client-server archive" },
  { name: "Cardguard", description: "Persevering transitional model" },
  { name: "Bitchip", description: "Advanced fresh-thinking hierarchy" },
  { name: "Trippledex", description: "Distributed maximized groupware" },
  { name: "Mat Lam Tam", description: "Streamlined cohesive alliance" },
  {
    name: "Fixflex",
    description: "Ameliorated transitional middleware",
    address: "tlocksley1f@pcworld.com",
  },
  {
    name: "Ventosanzap",
    description: "Enterprise-wide real-time installation",
    address: "emuldowney1g@nifty.com",
  },
  {
    name: "Quo Lux",
    description: "Progressive mobile concept",
    address: "csteade1h@independent.co.uk",
  },
  { name: "Y-Solowarm", description: "Function-based tertiary conglomeration" },
  {
    name: "Sub-Ex",
    description: "Face to face upward-trending customer loyalty",
  },
  {
    name: "Biodex",
    description: "Team-oriented multi-tasking capability",
    address: "cklimt1k@omniture.com",
  },
  {
    name: "Bitchip",
    description: "Universal stable framework",
    address: "tbilton1l@ucoz.com",
  },
  {
    name: "Namfix",
    description: "Customer-focused local artificial intelligence",
  },
  { name: "Aerified", description: "Exclusive fault-tolerant analyzer" },
  { name: "Hatity", description: "Intuitive maximized support" },
  {
    name: "Domainer",
    description: "User-friendly bottom-line collaboration",
    address: "mmattaser1p@google.ca",
  },
  { name: "Solarbreeze", description: "Managed foreground success" },
  {
    name: "Tempsoft",
    description: "Horizontal holistic artificial intelligence",
  },
  {
    name: "Subin",
    description: "Self-enabling bi-directional solution",
    address: "mcookson1s@berkeley.edu",
  },
  {
    name: "Zontrax",
    description: "Focused systematic instruction set",
    address: "rpadginton1t@storify.com",
  },
  { name: "Cookley", description: "Customer-focused bottom-line help-desk" },
  {
    name: "Zathin",
    description: "Compatible exuding array",
    address: "mcholdcroft1v@tinypic.com",
  },
  { name: "Domainer", description: "Networked full-range info-mediaries" },
  {
    name: "Zaam-Dox",
    description: "Upgradable executive budgetary management",
    address: "cnobriga1x@histats.com",
  },
  { name: "Tres-Zap", description: "Open-source impactful implementation" },
  { name: "Treeflex", description: "Horizontal full-range ability" },
  {
    name: "Sub-Ex",
    description: "Realigned tangible focus group",
    address: "ppiken20@multiply.com",
  },
  {
    name: "Andalax",
    description: "Automated 3rd generation circuit",
    address: "cfenn21@tumblr.com",
  },
  {
    name: "Wrapsafe",
    description: "Configurable context-sensitive focus group",
    address: "gpiggins22@java.com",
  },
  {
    name: "Lotlux",
    description: "Cross-platform uniform frame",
    address: "eglasson23@hexun.com",
  },
  {
    name: "Ventosanzap",
    description: "Enhanced zero defect monitoring",
    address: "fparrish24@eepurl.com",
  },
  { name: "Stringtough", description: "Advanced zero tolerance hardware" },
  {
    name: "Tres-Zap",
    description: "Optional directional analyzer",
    address: "jtieraney26@opensource.org",
  },
  {
    name: "Konklab",
    description: "Multi-tiered homogeneous system engine",
    address: "sdaffern27@netscape.com",
  },
  {
    name: "Bitwolf",
    description: "Managed didactic approach",
    address: "rgridon28@hibu.com",
  },
  {
    name: "Flowdesk",
    description: "Stand-alone responsive structure",
    address: "mdodamead29@wunderground.com",
  },
  {
    name: "Home Ing",
    description: "Enterprise-wide real-time challenge",
    address: "tpheazey2a@businesswire.com",
  },
  {
    name: "Solarbreeze",
    description: "Profit-focused high-level parallelism",
    address: "templeton2b@hexun.com",
  },
  { name: "Wrapsafe", description: "Stand-alone systemic workforce" },
  {
    name: "Redhold",
    description: "Customer-focused bi-directional standardization",
  },
  { name: "Namfix", description: "User-friendly directional framework" },
  { name: "Lotlux", description: "Networked clear-thinking open system" },
  {
    name: "Gembucket",
    description: "Up-sized human-resource focus group",
    address: "cbuttel2g@ca.gov",
  },
  { name: "Ronstring", description: "Configurable cohesive synergy" },
  {
    name: "Redhold",
    description: "Triple-buffered multi-tasking implementation",
  },
  {
    name: "Mat Lam Tam",
    description: "Optimized reciprocal framework",
    address: "npegler2j@berkeley.edu",
  },
  { name: "Opela", description: "Synergized value-added migration" },
  { name: "Transcof", description: "De-engineered well-modulated contingency" },
  {
    name: "Bigtax",
    description: "Front-line 4th generation conglomeration",
    address: "dwalbridge2m@unblog.fr",
  },
  {
    name: "Regrant",
    description: "Ergonomic mobile capacity",
    address: "obeauchamp2n@npr.org",
  },
  { name: "Konklab", description: "Configurable client-server monitoring" },
  { name: "Flexidy", description: "Focused full-range implementation" },
  { name: "Tempsoft", description: "Multi-lateral client-server secured line" },
  {
    name: "Konklux",
    description: "Managed asymmetric internet solution",
    address: "cgarie2r@twitter.com",
  },
];
